#! /bin/sh

## Copyright (C) 2023-2023 Aditya Sharma
##
## BSPWM configuration for LEGION



## Autostart ------------------------------------------------ #

pgrep -x sxhkd > /dev/null || sxhkd &  # Key-Bindings
picom &                                # Compositor
nitrogen --restore &		       # Wallpaper
dunst -c ~/.config/dunst/dunstrc &     # Notify
sh ~/.config/polybar/launch.sh &          # Polybar
#lxqt-policykit-agent &
lxsession &
sh ~/.config/conky/Botein/start.sh &
ksuperkey -e 'Super_L=Alt_L|F1'
ksuperkey -e 'Alt_L=Alt_L|F2'




# cursor correction
xsetroot -cursor_name left_ptr &


## Variables ------------------------------------------------ #

TERMINAL    = 'st'
BORDER      =  '10'
SPLIT_RATIO = '0.50'
WIN_GAP     = '10'


## Configurations ------------------------------------------- #

#bspc monitor -d 1 2 3 4 5
bspc monitor -d '' '' '' '' '' '' '' ''
#bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         3 
bspc config window_gap           "$WIN_GAP"
bspc config split_ratio          "$SPLIT_RATIO"
bspc config border_radius	 10

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#ffb86c" 

#bspc config focused_border_color "#8fbcbb" 
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#B4E3AD"
bspc config presel_feedback_color "#E5A3A1"



## Rules ---------------------------------------------------- #


bspc rule -a <WM_CLASS> state=floating rectangle=300x300+600+250

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Terminal
bspc rule -a '$TERMINAL' desktop='^1' follow=on focus=on
bspc rule -a xfce4-terminal desktop='^1' follow=on focus=on

# Nitrogen Wallpaper
bspc rule -a Nitrogen desktop='^8' focus=on follow=on state=floating rectangle=800x600 center=true

# HP Toolbox
bspc rule -a hp-toolbox desktop='^8' focus=on follow=on state=floating rectangle=800x600 center=true

# WebBrowser
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# FileManager
bspc rule -a Nemo desktop='^3' follow=on focus=on
bspc rule -a Pcmanfm desktop='^3' state=floating rectangle=800x500+0+0 center=true


bspc rule -a Firefox:Places state=floating rectangle=80x60 center=true 

# System Settings
bspc rule -a GParted desktop='^8' follow=on focus=on rectangle=800x600+0+0 center=true
bspc rule -a Lxpolkit -o state=floating follow=on focus=on rectangle=1000x600+500+500 center=true
bspc rule -a Xfce4-about -o state=floating follow=on focus=on rectangle=1000x600+500+500 center=true
bspc rule -a octopi desktop='^8' follow=on focus=on rectangle=800x600+0+0 center=true



#Pong Game
bspc rule -a StartupPrompt.py state=floating follow=on focus=on rectangle=450x250+0+0 center=true


declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# Always Floating Apps
declare -a floating=(alacritty-float Nitrogen Pcmanfm Timeshift-gtk Thunar Onboard Yad 'Firefox:Places' 'Firefox:File Upload' 
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating rectangle=800x600 center=true follow=on focus=on; done

xfce4-terminal -e "less $HOME/.config/help"
